import subprocess
from pathlib import Path


class PdfCompiler:
    """Responsible for compiling LaTeX to PDF."""

    def __init__(self, tex_file: Path):
        self.tex_file = tex_file

    def compile(self, clean: bool = True) -> None:
        """Compiles the TeX file using latexmk."""
        if not self.tex_file.exists():
            raise FileNotFoundError(f"TeX file not found for compilation: {self.tex_file}")

        print(f"⚙️ Compiling {self.tex_file.name}...")

        # Using latexmk is standard for automation
        # SECURITY: -no-shell-escape prevents \write18 and other shell command execution
        cmd = [
            "latexmk",
            "-pdf",
            "-no-shell-escape",
            "-interaction=nonstopmode",
            "-outdir=" + str(self.tex_file.parent),
            str(self.tex_file),
        ]

        try:
            subprocess.run(
                cmd,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
            )
            print("✅ PDF generated successfully.")

            if clean:
                self._clean_auxiliary_files()

        except subprocess.CalledProcessError as e:
            print("❌ Error during LaTeX compilation.")
            output = ""
            if e.stdout:
                output = e.stdout.decode("utf-8", errors="ignore")
            output_tail = output[-2000:] if output else ""
            if output_tail:
                print(output_tail)
            raise RuntimeError(f"LaTeX compilation failed. {output_tail}") from e

    def _clean_auxiliary_files(self):
        """Removes auxiliary files generated by LaTeX."""
        extensions = [".aux", ".log", ".out", ".fls", ".fdb_latexmk", ".synctex.gz"]

        stem = self.tex_file.stem
        parent = self.tex_file.parent

        for ext in extensions:
            aux_file = parent / (stem + ext)
            if aux_file.exists():
                aux_file.unlink()

        self._clean_main_tex()

        print("Temporary files cleaned up.")

    def _clean_main_tex(self):
        """Removes the main.tex file."""
        main_tex = "main.tex"
        parent = self.tex_file.parent
        main_tex_file = parent / main_tex
        if main_tex_file.exists():
            main_tex_file.unlink()
